# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\auswertungDialogGui.ui'
#
# Created: Wed May  7 16:09:06 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(970, 678)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/window-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("")
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(280, 30, 671, 621))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.label = QtGui.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(10, 10, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtGui.QTableWidget(self.page)
        self.tableWidget.setGeometry(QtCore.QRect(10, 470, 651, 141))
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setRowCount(3)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        self.frameEinsBalken = QtGui.QFrame(self.page)
        self.frameEinsBalken.setGeometry(QtCore.QRect(10, 70, 651, 341))
        self.frameEinsBalken.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameEinsBalken.setFrameShadow(QtGui.QFrame.Raised)
        self.frameEinsBalken.setObjectName("frameEinsBalken")
        self.label_4 = QtGui.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(30, 40, 31, 21))
        self.label_4.setObjectName("label_4")
        self.spinBox = QtGui.QSpinBox(self.page)
        self.spinBox.setGeometry(QtCore.QRect(70, 40, 61, 22))
        self.spinBox.setMinimum(1900)
        self.spinBox.setMaximum(2099)
        self.spinBox.setProperty("value", 2014)
        self.spinBox.setObjectName("spinBox")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_2 = QtGui.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tableWidget_2 = QtGui.QTableWidget(self.page_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 470, 651, 141))
        self.tableWidget_2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_2.setCornerButtonEnabled(False)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(14)
        self.tableWidget_2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(13, item)
        self.frameZweiPie = QtGui.QFrame(self.page_2)
        self.frameZweiPie.setGeometry(QtCore.QRect(10, 50, 651, 211))
        self.frameZweiPie.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameZweiPie.setFrameShadow(QtGui.QFrame.Raised)
        self.frameZweiPie.setObjectName("frameZweiPie")
        self.frameZweiVerlauf = QtGui.QFrame(self.page_2)
        self.frameZweiVerlauf.setGeometry(QtCore.QRect(10, 280, 651, 171))
        self.frameZweiVerlauf.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameZweiVerlauf.setFrameShadow(QtGui.QFrame.Raised)
        self.frameZweiVerlauf.setObjectName("frameZweiVerlauf")
        self.label_5 = QtGui.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(180, 10, 31, 21))
        self.label_5.setObjectName("label_5")
        self.spinBox_2 = QtGui.QSpinBox(self.page_2)
        self.spinBox_2.setGeometry(QtCore.QRect(220, 10, 61, 22))
        self.spinBox_2.setMinimum(1900)
        self.spinBox_2.setMaximum(2099)
        self.spinBox_2.setProperty("value", 2014)
        self.spinBox_2.setObjectName("spinBox_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_3 = QtGui.QLabel(self.page_3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frameDreiPie = QtGui.QFrame(self.page_3)
        self.frameDreiPie.setGeometry(QtCore.QRect(10, 50, 651, 211))
        self.frameDreiPie.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameDreiPie.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDreiPie.setObjectName("frameDreiPie")
        self.frameDreiVerlauf = QtGui.QFrame(self.page_3)
        self.frameDreiVerlauf.setGeometry(QtCore.QRect(10, 280, 651, 171))
        self.frameDreiVerlauf.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameDreiVerlauf.setFrameShadow(QtGui.QFrame.Raised)
        self.frameDreiVerlauf.setObjectName("frameDreiVerlauf")
        self.tableWidget_3 = QtGui.QTableWidget(self.page_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 470, 651, 141))
        self.tableWidget_3.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_3.setCornerButtonEnabled(False)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(14)
        self.tableWidget_3.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(13, item)
        self.label_6 = QtGui.QLabel(self.page_3)
        self.label_6.setGeometry(QtCore.QRect(170, 10, 31, 21))
        self.label_6.setObjectName("label_6")
        self.spinBox_3 = QtGui.QSpinBox(self.page_3)
        self.spinBox_3.setGeometry(QtCore.QRect(210, 10, 61, 22))
        self.spinBox_3.setMinimum(1900)
        self.spinBox_3.setMaximum(2099)
        self.spinBox_3.setProperty("value", 2014)
        self.spinBox_3.setObjectName("spinBox_3")
        self.stackedWidget.addWidget(self.page_3)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, -10, 271, 701))
        self.frame.setStyleSheet("QFrame#frame{\n"
"\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(199, 199, 199, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"}\n"
"\n"
"QToolButton{\n"
"background-color: transparent;\n"
"border: none;\n"
"\n"
"}\n"
"\n"
"QToolButton:checked, QToolButton:pressed{\n"
"background-color: rgb(193, 210, 238);\n"
"border: 1px solid rgb(60, 127, 177);\n"
"\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"background-color: rgb(224, 232, 246);\n"
"\n"
"}\n"
"\n"
"QToolButton:checked:hover{\n"
"background-color: rgb(193, 210, 238);\n"
"border: 1px solid rgb(60, 127, 177);\n"
"\n"
"}")
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButtonEA = QtGui.QPushButton(self.frame)
        self.pushButtonEA.setGeometry(QtCore.QRect(50, 100, 131, 31))
        self.pushButtonEA.setStyleSheet("")
        self.pushButtonEA.setCheckable(True)
        self.pushButtonEA.setChecked(True)
        self.pushButtonEA.setAutoExclusive(True)
        self.pushButtonEA.setObjectName("pushButtonEA")
        self.pushButtonEUE = QtGui.QPushButton(self.frame)
        self.pushButtonEUE.setGeometry(QtCore.QRect(50, 180, 131, 31))
        self.pushButtonEUE.setCheckable(True)
        self.pushButtonEUE.setAutoExclusive(True)
        self.pushButtonEUE.setObjectName("pushButtonEUE")
        self.pushButtonAUE = QtGui.QPushButton(self.frame)
        self.pushButtonAUE.setGeometry(QtCore.QRect(50, 250, 131, 31))
        self.pushButtonAUE.setCheckable(True)
        self.pushButtonAUE.setAutoExclusive(True)
        self.pushButtonAUE.setObjectName("pushButtonAUE")
        self.pushButtonSchliessen = QtGui.QPushButton(self.frame)
        self.pushButtonSchliessen.setGeometry(QtCore.QRect(60, 620, 131, 31))
        self.pushButtonSchliessen.setObjectName("pushButtonSchliessen")

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Auswertung", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Einnahmen / Ausgaben Vergleich:", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Einnahme", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Ausgabe", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.verticalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "Differenz", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Jan", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Feb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "Mrz", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "Apr", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "Mai", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog", "Jun", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Dialog", "Jul", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Dialog", "Aug", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("Dialog", "Sep", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("Dialog", "Okt", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(10).setText(QtGui.QApplication.translate("Dialog", "Nov", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(11).setText(QtGui.QApplication.translate("Dialog", "Dez", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Jahr:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Einnahmenübersicht:", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Farbe", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Einnahme", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "Jan", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "Feb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "Mrz", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog", "Apr", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Dialog", "Mai", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Dialog", "Jun", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("Dialog", "Jul", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("Dialog", "Aug", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(10).setText(QtGui.QApplication.translate("Dialog", "Sep", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(11).setText(QtGui.QApplication.translate("Dialog", "Okt", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(12).setText(QtGui.QApplication.translate("Dialog", "Nov", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_2.horizontalHeaderItem(13).setText(QtGui.QApplication.translate("Dialog", "Dez", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Jahr:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Ausgabenübersicht:", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Farbe", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Ausgabe", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("Dialog", "Jan", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("Dialog", "Feb", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("Dialog", "Mrz", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("Dialog", "Apr", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("Dialog", "Mai", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("Dialog", "Jun", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(8).setText(QtGui.QApplication.translate("Dialog", "Jul", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(9).setText(QtGui.QApplication.translate("Dialog", "Aug", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(10).setText(QtGui.QApplication.translate("Dialog", "Sep", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(11).setText(QtGui.QApplication.translate("Dialog", "Okt", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(12).setText(QtGui.QApplication.translate("Dialog", "Nov", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_3.horizontalHeaderItem(13).setText(QtGui.QApplication.translate("Dialog", "Dez", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Jahr:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonEA.setText(QtGui.QApplication.translate("Dialog", "Einnahmen/Ausgaben", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonEUE.setText(QtGui.QApplication.translate("Dialog", "Einnahmenübersicht", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAUE.setText(QtGui.QApplication.translate("Dialog", "Ausgabenübersicht", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSchliessen.setText(QtGui.QApplication.translate("Dialog", "Fenster schließen", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
