# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\hauptfenster.ui'
#
# Created: Sat May  3 18:57:28 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_hauptfensterObjekt(object):
    def setupUi(self, hauptfensterObjekt):
        hauptfensterObjekt.setObjectName("hauptfensterObjekt")
        hauptfensterObjekt.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/window-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        hauptfensterObjekt.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(hauptfensterObjekt)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 30, 131, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/b-buchung-hinzufuegen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 410, 741, 131))
        self.groupBox.setObjectName("groupBox")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 30, 91, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(110, 50, 61, 16))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: green")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(110, 70, 51, 16))
        self.label_3.setStyleSheet("color: red")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(200, 50, 51, 20))
        self.label_4.setStyleSheet("color: green")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.line = QtGui.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(110, 90, 141, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(200, 70, 51, 20))
        self.label_5.setStyleSheet("color: red")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(200, 100, 51, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(110, 100, 61, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(540, 40, 71, 16))
        self.label_8.setObjectName("label_8")
        self.line_2 = QtGui.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(540, 60, 131, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(620, 80, 46, 13))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(670, 80, 31, 16))
        self.label_10.setObjectName("label_10")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 100, 741, 291))
        self.groupBox_2.setObjectName("groupBox_2")
        self.treeWidget = QtGui.QTreeWidget(self.groupBox_2)
        self.treeWidget.setGeometry(QtCore.QRect(20, 30, 701, 241))
        self.treeWidget.setStyleSheet("")
        self.treeWidget.setObjectName("treeWidget")
        hauptfensterObjekt.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(hauptfensterObjekt)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtGui.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        self.menuOperationen = QtGui.QMenu(self.menubar)
        self.menuOperationen.setObjectName("menuOperationen")
        self.menuAuswertung = QtGui.QMenu(self.menubar)
        self.menuAuswertung.setObjectName("menuAuswertung")
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        hauptfensterObjekt.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(hauptfensterObjekt)
        self.statusbar.setObjectName("statusbar")
        hauptfensterObjekt.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(hauptfensterObjekt)
        self.toolBar.setObjectName("toolBar")
        hauptfensterObjekt.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNeue_Datenbank_erstellen = QtGui.QAction(hauptfensterObjekt)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/a-neue-datenbank.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNeue_Datenbank_erstellen.setIcon(icon2)
        self.actionNeue_Datenbank_erstellen.setObjectName("actionNeue_Datenbank_erstellen")
        self.actionDatenbank_laden = QtGui.QAction(hauptfensterObjekt)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/a-datenbank-laden.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDatenbank_laden.setIcon(icon3)
        self.actionDatenbank_laden.setObjectName("actionDatenbank_laden")
        self.actionDatenbank_loeschen = QtGui.QAction(hauptfensterObjekt)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/a-datenbank-loeschen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDatenbank_loeschen.setIcon(icon4)
        self.actionDatenbank_loeschen.setObjectName("actionDatenbank_loeschen")
        self.actionBeenden = QtGui.QAction(hauptfensterObjekt)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/a-beenden.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBeenden.setIcon(icon5)
        self.actionBeenden.setObjectName("actionBeenden")
        self.actionHilfe = QtGui.QAction(hauptfensterObjekt)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/d-hilfe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHilfe.setIcon(icon6)
        self.actionHilfe.setObjectName("actionHilfe")
        self.actionInfo = QtGui.QAction(hauptfensterObjekt)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/d-info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInfo.setIcon(icon7)
        self.actionInfo.setObjectName("actionInfo")
        self.actionEintrag_hinzufuegen = QtGui.QAction(hauptfensterObjekt)
        self.actionEintrag_hinzufuegen.setIcon(icon1)
        self.actionEintrag_hinzufuegen.setObjectName("actionEintrag_hinzufuegen")
        self.actionKategorien_verwalten = QtGui.QAction(hauptfensterObjekt)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/b-kategorien-verwalten.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionKategorien_verwalten.setIcon(icon8)
        self.actionKategorien_verwalten.setObjectName("actionKategorien_verwalten")
        self.actionEintrag_loeschen = QtGui.QAction(hauptfensterObjekt)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/b-buchung-loeschen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEintrag_loeschen.setIcon(icon9)
        self.actionEintrag_loeschen.setObjectName("actionEintrag_loeschen")
        self.actionBuchung_editieren = QtGui.QAction(hauptfensterObjekt)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/b-buchung-editieren.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBuchung_editieren.setIcon(icon10)
        self.actionBuchung_editieren.setObjectName("actionBuchung_editieren")
        self.actionBuchungen_auswerten = QtGui.QAction(hauptfensterObjekt)
        self.actionBuchungen_auswerten.setObjectName("actionBuchungen_auswerten")
        self.menuDatei.addAction(self.actionNeue_Datenbank_erstellen)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionDatenbank_laden)
        self.menuDatei.addAction(self.actionDatenbank_loeschen)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionBeenden)
        self.menuOperationen.addAction(self.actionEintrag_hinzufuegen)
        self.menuOperationen.addAction(self.actionBuchung_editieren)
        self.menuOperationen.addAction(self.actionEintrag_loeschen)
        self.menuOperationen.addSeparator()
        self.menuOperationen.addAction(self.actionKategorien_verwalten)
        self.menuAuswertung.addAction(self.actionBuchungen_auswerten)
        self.menu.addAction(self.actionHilfe)
        self.menu.addAction(self.actionInfo)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuOperationen.menuAction())
        self.menubar.addAction(self.menuAuswertung.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.actionEintrag_hinzufuegen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionKategorien_verwalten)

        self.retranslateUi(hauptfensterObjekt)
        QtCore.QMetaObject.connectSlotsByName(hauptfensterObjekt)

    def retranslateUi(self, hauptfensterObjekt):
        hauptfensterObjekt.setWindowTitle(QtGui.QApplication.translate("hauptfensterObjekt", "Haushaltsbuch", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Buchung hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("hauptfensterObjekt", "Übersicht:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Alle Buchungen:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Einnahmen:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Ausgaben:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("hauptfensterObjekt", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("hauptfensterObjekt", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("hauptfensterObjekt", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Differenz:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Kontostand:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("hauptfensterObjekt", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("hauptfensterObjekt", "€", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("hauptfensterObjekt", "Letzte Buchungen:", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("hauptfensterObjekt", "Datum:", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("hauptfensterObjekt", "Typ:", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(2, QtGui.QApplication.translate("hauptfensterObjekt", "Kategorie:", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(3, QtGui.QApplication.translate("hauptfensterObjekt", "Beschreibung:", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(4, QtGui.QApplication.translate("hauptfensterObjekt", "Betrag:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatei.setTitle(QtGui.QApplication.translate("hauptfensterObjekt", "Datei", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOperationen.setTitle(QtGui.QApplication.translate("hauptfensterObjekt", "Operationen", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAuswertung.setTitle(QtGui.QApplication.translate("hauptfensterObjekt", "Auswertung", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("hauptfensterObjekt", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("hauptfensterObjekt", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNeue_Datenbank_erstellen.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Neue Datenbank erstellen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDatenbank_laden.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Datenbank laden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDatenbank_loeschen.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Datenbank löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeenden.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHilfe.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Hilfe", None, QtGui.QApplication.UnicodeUTF8))
        self.actionInfo.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEintrag_hinzufuegen.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Buchung hinzufügen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKategorien_verwalten.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Kategorien verwalten", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEintrag_loeschen.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Buchung löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuchung_editieren.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Buchung editieren", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuchungen_auswerten.setText(QtGui.QApplication.translate("hauptfensterObjekt", "Buchungen auswerten", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
